apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.filebeat.serviceAccount.name }}
  namespace: {{ .Release.Namespace }}
  
---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: nodes-pods-clusterrole
rules:
  - apiGroups: [""]
    resources: ["nodes","pods","namespaces"]
    verbs: ["get", "watch", "list"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: read-nodes-pods-global
subjects:
  - kind: ServiceAccount
    name: {{ .Values.filebeat.name }} 
    namespace: {{ .Release.Namespace }}
roleRef: 
  kind: ClusterRole
  name:  nodes-pods-clusterrole
  apiGroup: rbac.authorization.k8s.io